#!/bin/bash
# This script can be used to install fake-service and its dependencies. This script has been tested with the following
# operating systems:
#
# 1. Ubuntu 20.04

set -e

readonly DEFAULT_INSTALL_PATH="/opt/fake-service"
readonly DEFAULT_FAKESERVICE_USER="fake-service"
readonly DOWNLOAD_PACKAGE_PATH="/tmp/fake-service.zip"

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SYSTEM_BIN_DIR="/usr/local/bin"

readonly SCRIPT_NAME="$(basename "$0")"

function print_usage {
  echo
  echo "Usage: install-fake-service [OPTIONS]"
  echo
  echo "This script can be used to install fake-service and its dependencies. This script has been tested with Ubuntu 20.04."
  echo
  echo "Options:"
  echo
  echo -e "  --version\t\tThe version of fake-service to install. Optional if download-url is provided."
  echo -e "  --download-url\t\tUrl to exact fake-service package to be installed. Optional if version is provided."
  echo -e "  --path\t\tThe path where fake-service should be installed. Optional. Default: $DEFAULT_INSTALL_PATH."
  echo -e "  --user\t\tThe user who will own the fake-service install directories. Optional. Default: $DEFAULT_FAKESERVICE_USER."
  echo
  echo "Example:"
  echo
  echo "  install-fake-service --version 0.5.1"
}

function log {
  local -r level="$1"
  local -r message="$2"
  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}

function log_info {
  local -r message="$1"
  log "INFO" "$message"
}

function log_warn {
  local -r message="$1"
  log "WARN" "$message"
}

function log_error {
  local -r message="$1"
  log "ERROR" "$message"
}

function assert_not_empty {
  local -r arg_name="$1"
  local -r arg_value="$2"

  if [[ -z "$arg_value" ]]; then
    log_error "The value for '$arg_name' cannot be empty"
    print_usage
    exit 1
  fi
}

function assert_either_or {
  local -r arg1_name="$1"
  local -r arg1_value="$2"
  local -r arg2_name="$3"
  local -r arg2_value="$4"

  if [[ -z "$arg1_value" && -z "$arg2_value" ]]; then
    log_error "Either the value for '$arg1_name' or '$arg2_name' must be passed, both cannot be empty"
    print_usage
    exit 1
  fi
}

# A retry function that attempts to run a command a number of times and returns the output
function retry {
  local -r cmd="$1"
  local -r description="$2"

  for i in $(seq 1 5); do
    log_info "$description"

    # The boolean operations with the exit status are there to temporarily circumvent the "set -e" at the
    # beginning of this script which exits the script immediatelly for error status while not losing the exit status code
    output=$(eval "$cmd") && exit_status=0 || exit_status=$?
    log_info "$output"
    if [[ $exit_status -eq 0 ]]; then
      echo "$output"
      return
    fi
    log_warn "$description failed. Will sleep for 10 seconds and try again."
    sleep 10
  done;

  log_error "$description failed after 5 attempts."
  exit $exit_status
}

function has_yum {
  [ -n "$(command -v yum)" ]
}

function has_apt_get {
  [ -n "$(command -v apt-get)" ]
}

# As dependencies are installed from 'install-consul' script, the function 'install_dependencies' is intentionally commented out

# function install_dependencies {
#   log_info "Installing dependencies"

#   if has_apt_get; then
#     sudo apt-get update -y
#     sudo apt-get install -y awscli curl unzip jq
#   elif has_yum; then
#     sudo yum update -y
#     sudo yum install -y aws curl unzip jq
#   else
#     log_error "Could not find apt-get or yum. Cannot install dependencies on this OS."
#     exit 1
#   fi
# }

function user_exists {
  local -r username="$1"
  id "$username" >/dev/null 2>&1
}

function create_fake_service_user {
  local -r username="$1"

  if user_exists "$username"; then
    echo "User $username already exists. Will not create again."
  else
    log_info "Creating user named $username"
    sudo useradd "$username"
  fi
}

function create_fake_service_install_paths {
  local -r path="$1"
  local -r username="$2"

  log_info "Creating install dirs for fake-service at $path"
  sudo mkdir -p "$path"
  sudo mkdir -p "$path/bin"
  sudo mkdir -p "$path/config"

  log_info "Changing ownership of $path to $username"
  sudo chown -R "$username:$username" "$path"
}

function fetch_binary {
  local -r version="$1"
  local download_url="$2"

  local cpu_arch
  cpu_arch="$(uname -m)"
  local binary_arch=""
  case "$cpu_arch" in
    x86_64)
      binary_arch="amd64"
      ;;
    x86)
      binary_arch="386"
      ;;
    arm64|aarch64)
      binary_arch="arm64"
      ;;
    arm*)
      # The following info is taken from https://github.com/nicholasjackson/fake-service/releases
      #
      # Note for ARM users:
      #
      # Use Armelv5 for all 32-bit armel systems
      # Use Armhfv6 for all armhf systems with v6+ architecture
      # Use Arm64 for all v8 64-bit architectures
      # The following commands can help determine the right version for your system:
      #
      # $ uname -m
      # $ readelf -a /proc/self/exe | grep -q -c Tag_ABI_VFP_args && echo "armhf" || echo "armel"
      #
      local vfp_tag
      vfp_tag="$(readelf -a /proc/self/exe | grep -q -c Tag_ABI_VFP_args)"
      if [[ -z $vfp_tag  ]]; then
        binary_arch="armelv5"
      else
        binary_arch="armhfv6"
      fi
      ;;
    *)
      log_error "CPU architecture $cpu_arch is not a supported by fake-service."
      exit 1
      ;;
    esac

  if [[ -z "$download_url" && -n "$version" ]]; then
    download_url="https://github.com/nicholasjackson/fake-service/releases/download/v${version}/fake_service_linux_${binary_arch}.zip"
  fi

  retry \
    "curl -o'$DOWNLOAD_PACKAGE_PATH' '$download_url' --location --remote-header-name --remote-name --silent --fail --show-error" \
    "Downloading fake-service to $DOWNLOAD_PACKAGE_PATH"
}

function install_binary {
  local -r install_path="$1"
  local -r username="$2"

  local -r bin_dir="$install_path/bin"
  local -r fake_service_dest_path="$bin_dir/fake-service"
  local -r run_fake_service_dest_path="$bin_dir/run-fake-service"

  unzip -d /tmp "$DOWNLOAD_PACKAGE_PATH"

  log_info "Moving fake-service binary to $fake_service_dest_path"
  sudo mv "/tmp/fake-service" "$fake_service_dest_path"
  sudo chown "$username:$username" "$fake_service_dest_path"
  sudo chmod a+x "$fake_service_dest_path"

  local -r symlink_path="$SYSTEM_BIN_DIR/fake-service"
  if [[ -f "$symlink_path" ]]; then
    log_info "Symlink $symlink_path already exists. Will not add again."
  else
    log_info "Adding symlink to $fake_service_dest_path in $symlink_path"
    sudo ln -s "$fake_service_dest_path" "$symlink_path"
  fi

  log_info "Copying fake-service run script to $run_fake_service_dest_path"
  sudo cp "$SCRIPT_DIR/run-fake-service" "$run_fake_service_dest_path"
  sudo chown "$username:$username" "$run_fake_service_dest_path"
  sudo chmod a+x "$run_fake_service_dest_path"
}

function install {
  local version=""
  local download_url=""
  local path="$DEFAULT_INSTALL_PATH"
  local user="$DEFAULT_FAKESERVICE_USER"

  while [[ $# -gt 0 ]]; do
    local key="$1"

    case "$key" in
      --version)
        version="$2"
        shift
        ;;
      --download-url)
        download_url="$2"
        shift
        ;;
      --path)
        path="$2"
        shift
        ;;
      --user)
        user="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_either_or "--version" "$version" "--download-url" "$download_url"
  assert_not_empty "--path" "$path"
  assert_not_empty "--user" "$user"

  log_info "Starting fake-service install"
  
  # As dependencies are installed from 'install-consul' script, the function 'install_dependencies' is intentionally commented out
  # install_dependencies
  create_fake_service_user "$user"
  create_fake_service_install_paths "$path" "$user"

  fetch_binary "$version" "$download_url"
  install_binary "$path" "$user"

  # This command is run with sudo rights so that it will succeed in cases where image hardening alters the permissions
  # on the directories where fake-service may be installed.
#  if sudo -E PATH=$PATH bash -c "command fake-service"; then
#    log_info "fake-service install complete!";
#  else
#    log_info "Could not find fake-service command. Aborting.";
#    exit 1;
#  fi
}

install "$@"